blank_issues_enabled: true
contact_links:
  - name: Plugin Support
    url: https://wordpress.org/support/plugin/simple-smtp/
    about: Request help on the WordPress plugin page. Please bear in mind that this is a community/open-source plugin and support is not guaranteed.
