name: Feature Request
description: Request what you would like to see in an upcoming version.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Request a Feature

        Describe what you would like to see, the more detail the better. For semi-complex suggestions, diagrams/mock-ups are always appreciated.

        The plugin foundation is on the concept of simplicity and native-looking design. Suggestions and PRs outside of this remit are likely to be declined. In these scenarios, a reminder that the plugin is open-source - try your hand at your own version!

        **If you are planning to make a pull request, please still fill out the form and associate the PR with the issue**. Otherwise your PR may be rejected. Also [familiarise yourself with the contributing guidelines](https://github.com/soup-bowl/wp-simple-smtp/blob/develop/.github/CONTRIBUTING.md).

        ---
  - type: textarea
    id: description
    attributes:
      label: Describe your desired feature
      description: Go into as much detail as you possibly can.
    validations:
      required: true
