name: Deploy to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Composer Dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: simple-smtp

    - name: Upload release asset
      run: |
        gh release upload ${{ github.event.release.tag_name }} ${{ steps.deploy.outputs.zip-path }} --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
