name: Deploy to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-changelog:
    uses: soup-bowl/wordpress-workflows/.github/workflows/generate-changelog.yml@main
    with:
      repository: soup-bowl/wp-simple-smtp
    secrets: inherit

  tag:
    name: New tag
    runs-on: ubuntu-latest
    needs: generate-changelog

    steps:
    - uses: actions/checkout@v3

    - name: Update Readme
      run: |
        # Generate changelog.
        echo "${{ needs.generate-changelog.outputs.changelog }}" | base64 --decode >> readme.txt
        # Update version number.
        sed -i 's/{{VERSION_NUMBER}}/${{ github.event.release.tag_name }}/g' readme.txt
        sed -i 's/development-build/${{ github.event.release.tag_name }}/g' wp-simple-smtp.php

    - name: Composer Dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        dry-run: ${{ github.event.release.prerelease }}
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: simple-smtp

    - name: Upload release asset
      run: |
        gh release upload ${{ github.event.release.tag_name }} ${{ steps.deploy.outputs.zip-path }} --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
